[versions]
agp        = "8.13.0"
kotlin     = "2.2.20"
sdkMin     = "21"
sdkCompile = "36"
sdkTarget  = "36"
constraintlayout = "2.2.1"

[libraries]
androidx-core-ktx   = "androidx.core:core-ktx:1.15.0"
androidx-appcompat  = "androidx.appcompat:appcompat:1.7.1"
androidx-material   = "com.google.android.material:material:1.10.0"
androidx-constraint = "androidx.constraintlayout:constraintlayout:2.2.1"

#
# slf4j
#
slf4j-api       = 'org.slf4j:slf4j-api:2.0.17'
slf4j-logback   = 'com.github.tony19:logback-android:3.0.0'

#
# commons
#
common-gson      = 'com.google.code.gson:gson:2.13.2'
common-guava     = 'com.google.guava:guava:33.5.0-android'
common-joor      = 'org.jooq:joor-java-8:0.9.15'                                # https://github.com/jOOQ/jOOR
common-xposed    = 'com.wind.xposed:xposed-api-lib:0.1.3'
common-framework = 'com.rover12421.android.hide:framework:10.0.0_r2'            # https://github.com/rover12421/AndroidHideApi | https://mvnrepository.com/artifact/com.rover12421.android.hide/framework
common-xpeng     = 'io.github.xpeng:car:0.0.1'

[plugins]
android-application = { id = "com.android.application"     , version.ref = "agp"    }
kotlin-android      = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

